### ISSUE TITLE
Register User

### ISSUE THREAD

**Issue by Zweanslord** [Zweanslord/Stersectas#12]
As potential user
I want to register myself as a new user
So I can join Stersectas

Includes:
- Registration screen
- Registration link
- Password length validation

**Comment by MBons** [comment]
password length: 8 - 100

**Comment by MBons** [comment]
basic implementation done.

todo:
- email validation
- error messages

**Comment by MBons** [comment]
email confirmation implemented

**Comment by Zweanslord** [comment]
Added internationalization and mail template to verification email
